# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstack_dashboard', '0005_auto_20180821_1415'),
        ('openstack_dashboard', '0002_auto_20180722_1641'),
    ]

    operations = [
    ]
