# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-04 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack_dashboard', '0006_merge_20180904_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertdomain',
            name='domainname',
            field=models.CharField(blank=True, help_text='\u5728\u8be5\u7814\u7a76\u9886\u57df\u7814\u7a76\u7684\u5b66\u79d1\u540d\u79f0', max_length=32, verbose_name='*\u5b66\u79d1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='expertdomain',
            name='domaintype',
            field=models.CharField(blank=True, choices=[('\u56fd\u5bb6\u79d1\u6280\u90e8\u9886\u57df', '\u56fd\u5bb6\u79d1\u6280\u90e8\u9886\u57df'), ('\u56fd\u5bb6\u57fa\u91d1\u59d4\u9886\u57df', '\u56fd\u5bb6\u57fa\u91d1\u59d4\u9886\u57df'), ('\u884c\u4e1a\u5206\u7c7b', '\u884c\u4e1a\u5206\u7c7b'), ('\u4e2d\u56fe\u5206\u7c7b', '\u4e2d\u56fe\u5206\u7c7b')], help_text='\u7814\u7a76\u9886\u57df\u6240\u5c5e\u5206\u7c7b', max_length=32, verbose_name='*\u9886\u57df\u5206\u7c7b'),
        ),
    ]
